name: 游 Diagn칩stico Autom치tico do Projeto
description: O agente far치 uma varredura completa para descobrir por que o Narrativas-Chronoscribe n칚o est치 gerando conte칰do.
title: "[AutoDiagn칩stico] Analisar o projeto e corrigir falhas de gera칞칚o"
labels: ["auto", "diagnostico", "agente"]
assignees:
  - github-copilot
body:
  - type: markdown
    attributes:
      value: |
        ## 游 Diagn칩stico Autom치tico do Narrativas-Chronoscribe
        Este chamado acionar치 o agente configurado em `.github/agents/my-agent.md`.
        Ele tentar치 descobrir:
        - Por que o app **n칚o est치 gerando conte칰do**.
        - Quais erros est칚o impedindo o funcionamento.
        - E far치 **corre칞칫es autom치ticas**, quando poss칤vel.

        ---
        游빌 **O que voc칡 precisa fazer:**  
        Basta criar esta issue e esperar o agente agir.  
        Ele abrir치 PRs ou coment치rios explicando o que encontrou.

  - type: checkboxes
    id: confirmacao
    attributes:
      label: Confirma칞칚o
      options:
        - label: "Concordo em permitir que o agente fa칞a altera칞칫es autom치ticas e crie PRs no reposit칩rio"
          required: true

